version: '3.7'

services: 
    php:
        image: php:7.4-apache
        ports:
          - 8080:80
        volumes:
            - ./webroot/:/var/www/html/

volumes:
  persistent:

# do prikazove radky napiste:
# docker-compose up -d
# docker-compose down

volumes: 
    data: